services:
  - type: web
    name: anytimeanywherestrategy
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120 --workers 1 --worker-class gthread --threads 4
    envVars:
      - key: ANGEL_API_KEY
        sync: false
      - key: ANGEL_CLIENT_CODE
        sync: false
      - key: ANGEL_PASSWORD
        sync: false
      - key: ANGEL_TOTP_SECRET
        sync: false
